# Dockerfile

# Use the official Maven image to build the app
FROM maven:3.8.4-openjdk-17 AS builder
WORKDIR /app
COPY . /app
RUN mvn clean package

# Use the OpenJDK image to run the app
FROM openjdk:17-jdk-slim
COPY --from=builder /app/target/my-app.jar /app/my-app.jar
ENTRYPOINT ["java", "-jar", "/app/my-app.jar"]
